export const mockAnimes = [
    {
      id: 1,
      title: "Shadow Blades",
      genre: ["Action", "Ninja", "Fantasy"],
      description: "In a hidden realm, ninja clans fight for control of ancient relics.",
      image: "https://cdn.example.com/anime/shadowblades.jpg",
      rating: 8.4,
    },
    {
      id: 2,
      title: "Cyber Drift",
      genre: ["Sci-Fi", "Racing", "Thriller"],
      description: "In a futuristic city, illegal racers use AI-powered cars to win at all costs.",
      image: "https://cdn.example.com/anime/cyberdrift.jpg",
      rating: 7.9,
    },
    {
      id: 3,
      title: "Petal Hearts",
      genre: ["Romance", "Drama", "Slice of Life"],
      description: "A quiet girl and a transfer student bond over a love of flowers and poetry.",
      image: "https://cdn.example.com/anime/petalhearts.jpg",
      rating: 8.1,
    },
    {
      id: 4,
      title: "Steel Titan X",
      genre: ["Mecha", "Military", "Action"],
      description: "A teenage pilot discovers a legendary mech buried beneath the war zone.",
      image: "https://cdn.example.com/anime/steeltitanx.jpg",
      rating: 8.6,
    },
    {
      id: 5,
      title: "Ghost Archive",
      genre: ["Supernatural", "Mystery", "Horror"],
      description: "A student uncovers cursed books that summon spirits with unresolved pasts.",
      image: "https://cdn.example.com/anime/ghostarchive.jpg",
      rating: 8.0,
    },
    {
      id: 6,
      title: "Starbound Saga",
      genre: ["Adventure", "Sci-Fi", "Space Opera"],
      description: "A crew of misfits travels the galaxy searching for a mythical star map.",
      image: "https://cdn.example.com/anime/starboundsaga.jpg",
      rating: 8.3,
    },
    {
      id: 7,
      title: "Crimson Melody",
      genre: ["Music", "Drama", "School"],
      description: "A shy pianist joins a rebellious band and finds the courage to shine.",
      image: "https://cdn.example.com/anime/crimsonmelody.jpg",
      rating: 7.8,
    },
    {
      id: 8,
      title: "Time Weaver",
      genre: ["Fantasy", "Time Travel", "Drama"],
      description: "An orphan discovers he can manipulate time through ancient runes.",
      image: "https://cdn.example.com/anime/timeweaver.jpg",
      rating: 8.7,
    },
    {
      id: 9,
      title: "Arcane Cuisine",
      genre: ["Comedy", "Fantasy", "Cooking"],
      description: "A young chef attends a magical culinary academy to learn legendary recipes.",
      image: "https://cdn.example.com/anime/arcanecuisine.jpg",
      rating: 7.6,
    },
    {
      id: 10,
      title: "Neon Dreams",
      genre: ["Cyberpunk", "Romance", "Psychological"],
      description: "In a city of illusions, a hacker searches for truth and connection.",
      image: "https://cdn.example.com/anime/neondreams.jpg",
      rating: 8.5,
    }
  ];
  
  